### ISSUE TITLE
Can you please share sample credentials that you have in you firebase collection for login? Also captcha is not appearing.

### ISSUE THREAD

**Issue by Divijkatyal0406** [Aficionado45/Aadhaar_Address_Update#13]

**Comment by Aficionado45** [comment]
Right now this application won't work, we're given exculsive virtual enviornment and access to official APIs for testing purposes which was revoked later on.

**Comment by Divijkatyal0406** [comment]
Got it. So are there publicly available test API's by UDAI along with the documentation?

**Comment by Aficionado45** [comment]
No those were private APIs
